INSERT INTO RECIPES(ID, NAME, TYPE, SERVING_CAPACITY, INGREDIENTS, INSTRUCTIONS)
VALUES (101, 'DISH1', 'VEG', 3, '[{"name": "potato"}]', 'Oven');
INSERT INTO RECIPES(ID, NAME, TYPE, SERVING_CAPACITY, INGREDIENTS, INSTRUCTIONS)
VALUES (102, 'DISH2', 'VEG', 3, '[{"name": "tomato"}]', 'normal');
INSERT INTO RECIPES(ID, NAME, TYPE, SERVING_CAPACITY, INGREDIENTS, INSTRUCTIONS)
VALUES (103, 'DISH3', 'VEG', 3, '[{"name": "potato"}, {"name": "tomato"}]', 'Oven');
INSERT INTO RECIPES(ID, NAME, TYPE, SERVING_CAPACITY, INGREDIENTS, INSTRUCTIONS)
VALUES (104, 'DISH4', 'NON-VEG', 3, '[{"name": "chicken"}]', 'Oven');