CREATE TABLE RECIPES(
ID NUMBER NOT NULL,
NAME VARCHAR2(30) NOT NULL,
TYPE VARCHAR2(10) NOT NULL,
CREATION_DATE DATE default CURRENT_TIMESTAMP,
SERVING_CAPACITY NUMBER,
INGREDIENTS VARCHAR2(50),
INSTRUCTIONS VARCHAR2(50)
);
